#!/usr/bin/env python3
"""Emit an Inter font TTF as a C uint8_t array for embedding in the GUI."""
import sys
from pathlib import Path

def emit(input_path: Path, output_path: Path, symbol: str) -> None:
    data = input_path.read_bytes()
    lines = [
        "// Auto-generated by gui/fonts/embed_ttf.py. Do not edit by hand.",
        f"// Source: {input_path.name} ({len(data)} bytes)",
        "// Licensed under SIL Open Font License 1.1 (see Inter-LICENSE.txt).",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        f"static const std::size_t {symbol}_size = {len(data)};",
        f"static const std::uint8_t {symbol}_data[] = {{",
    ]
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    output_path.write_text("\n".join(lines))

if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    targets = [
        ("Inter-Regular.ttf",       "inter_regular.inl",      "kInterRegular"),
        ("JetBrainsMono-Regular.ttf", "jetbrains_mono.inl",   "kJetBrainsMono"),
    ]
    for ttf, inl, sym in targets:
        emit(here / ttf, here / inl, sym)
        print(f"Wrote {(here / inl).relative_to(here.parent.parent)}")
